### ISSUE TITLE
Type handler version '1210.12' could not be found in the extension repository

### ISSUE THREAD

**Issue by tfnaylor** [chef-partners/azure-chef-extension#70]
This issue seems to have reappeared suddenly today. There is an earlier (July-August) issue that was closed when it was resolved. We have tried US West and North Europe data centers and it is the same in both.

This is breaking a critical demo application for one of our customers so we are requesting attention on this ASAP.

**Comment by MarianoMunoz** [comment]
I am also suddenly experiencing this error with the chef extension when deploying my ubuntu (14.04.2-LTS) VMs with Azure Resource Manager. This was working without issue yesterday. I have the extension set to a type of "LinuxChefClient", with the typeHandlerVersion set to "1210.12".

I do not see that the extension version has changed or was deprecated in the change log or release notes.

I receive the following error:
{"error":{"code":"ArtifactNotFound","message":"Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository."}}

Any help with this issue would be appreciated. My deployment pipeline is currently blocked due to this unexpected issue.

**Comment by siddheshwar-more** [comment]
@tfnaylor  @MarianoMunoz 

We are verifying this issue with the help of https://github.com/Azure/azure-quickstart-templates/tree/master/chef-json-parameters-ubuntu-vm 

I'll post update here. Thanks!

**Comment by aarsan** [comment]
I got this as well in the 'Central US' region, today.

**Comment by siddheshwar-more** [comment]
Hello 
@tfnaylor  @MarianoMunoz 

We have verified this issue with [template](https://gist.github.com/siddheshwar-more/524018096b8963769563) and [template parameter](https://gist.github.com/siddheshwar-more/73cd3d2c6000c35b94e1) files. And its working fine for us.

We used ***azure-xplat-cli*** with below commands - 
```
azure config mode arm
azure login 
azure location list
azure group create <resource_group_name> <location> -f <above-template-file-path> -d <deployment-name> -e <above-template-file-params-file-path>
````

Could you please try with above shared template and let us know?
Or please share your template files and CLI tool(i.e Azure PowerShell or Azure-xplat-cli)) details.

Thank you!

**Comment by siddheshwar-more** [comment]
^ @aarsan

**Comment by aarsan** [comment]
Just attempted to deploy again and received the following error:

    {"error":{"code":"ArtifactNotFound","message":"Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository."}}

I am using the Python SDK, which is also what I used last night (which worked then).

**Comment by siddheshwar-more** [comment]
@aarsan 
Could you please share the python script that you are using? So we can try at our end quickly.

**Comment by aarsan** [comment]
This sounds more like an Azure problem than an extension problem. I'm assuming Azure uses name resolution to find the location of the extensions and that part seems to be not working from all locations. Because it works for you doesn't mean it should work for everyone. I just changed the API version to '2015-05-01-preview' from '2015-06-15' and it still doesn't work. I will downgrade my extension version to see if that makes a difference.

**Comment by aarsan** [comment]
If I change it to '1207.12' works. So, something is definitely wrong with '1210.12'

**Comment by tfnaylor** [comment]
We are using Azure Resource Manager to deploy our templates. The same template was working fine the day before yesterday and nothing changed on our side.

I am surprised we are going through this again. The exact same thing happened in July and someone on your side figured out that it had to do with your Azure account having special privileges for this particular resource so you don't see the problem. I guarantee you that this has nothing to do with our templates or our approach to deploying them - the problem is in Azure and you guys fixed it in August so you just need to take the same approach now. Please review the issue (now closed) from the previous occurrence of this problem.

**Comment by tfnaylor** [comment]
Here is a link to the previous (closed) occurrence of this issue. Note that NimishaS ultimately acknowledged the issue on your side and fixed it. Please consult her on this.

https://github.com/chef-partners/azure-chef-extension/issues/54

**Comment by MarianoMunoz** [comment]
I created a deployment using the same template you linked - https://github.com/Azure/azure-quickstart-templates/tree/master/chef-json-parameters-ubuntu-vm

I can confirm that I received the same error as before:
Status: NotFound
Type: Microsoft.Compute/virtualMachines/extensions
Resource: cheftest/LinuxChefExtension
StatusMessage:
{"error":{"code":"ArtifactNotFound","message":"Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository."}}

I get the same error using different subscriptions and accounts.

The deployment is created, but fails at the step where the chef client would be installed. It appears the extension is not available when azure attempts to fetch it from the repository.

**Comment by MarianoMunoz** [comment]
@aarsan 
I can confirm that changing the version from '1210.12' to  '1207.12' works on my side as well.

@siddheshwar-more 
It appears that we have simply lost access to the latest extension in the repository. There was a fix that I needed in 1210.12 for my deployments.

What guarantee do we have in the future that releases/builds won't suddenly be removed from the azure extension repository? Should I instead be opening an Azure support ticket for these types of issues, since it affects the Azure platform as well?

**Comment by aarsan** [comment]
Please post an update to this problem.

**Comment by siddheshwar-more** [comment]
@aarsan 
Yes, we are working with Azure team.
Thanks

**Comment by aarsan** [comment]
Thanks!

**Comment by NimishaS** [comment]
@tfnaylor, @aarsan, @MarianoMunoz, azure seems to have difficulty in handling the cases where we republish an internal extension more than once. We had published linux extension `1210.12.4.1001` recently to support centos where we republished internal extension more than once for testing.
Right now we have published linux extension `1210.12.4.2000` to fix this issue. Please verify.

**Comment by tfnaylor** [comment]
I am still getting the same error:
ArtifactNotFound : Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository.

This is causing serious problems for me with my customer right now...

**Comment by MarianoMunoz** [comment]
I received the following error when using "1210.12.4.2000" as the typeHandler version:
{"error":{"code":"InvalidParameter","target":"typeHandlerVersion","message":"The value of parameter typeHandlerVersion is invalid."}}

I also retried with the value "1210.12" to recheck and got the following:
{"error":{"code":"ArtifactNotFound","message":"Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository."}}

**Comment by NimishaS** [comment]
I have deleted extension `1210.12.4.1001` which was causing the issue. Last time this had fixed the issue.
I would request you to try once again. If this doesn't work then we'll take more assistance from Azure team.

**Comment by tfnaylor** [comment]
I still get the same failure:
ArtifactNotFound : Extension with publisher 'Chef.Bootstrap.WindowsAzure', type 'LinuxChefClient', and type handler version '1210.12' could not be found in the extension repository.

**Comment by MarianoMunoz** [comment]
@NimishaS Thank You. I have successfully deployed to Azure Resource Manager using typeHandler "1210.12".

It may have taken a while for the version to propagate through the azure systems, because I initially got a failure as well, but the following deployments worked without issue.

**Comment by tfnaylor** [comment]
Working for me as well - thank you.

Are you guys working to make sure this kind of thing doesn't happen in the future? Obviously it is very disruptive and in my particular case it could drive me customer to want to avoid Chef in their solution.

**Comment by aarsan** [comment]
To add to @tfnaylor , we are heavily investing in this extension rather than bootstrapping our nodes from the front door. It is extremely disruptive to our production and development environments. I appreciate all your hard work but without this service being reliable, we will have to avoid it.
